SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE discussion;
ALTER TABLE discussion ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE opinion;
ALTER TABLE opinion ALTER COLUMN id RESTART WITH 1;

SET FOREIGN_KEY_CHECKS = 1;
